name: Black Duck SCA
on:
  push:
    branches: [main, master, develop, stage, release]
  pull_request:
    branches: [main, master, develop, stage, release]
  workflow_dispatch: {}
permissions:
  contents: read
  security-events: write
jobs:
  scan:
    uses: acre-Australia/.github-private/.github/workflows/_blackducksca.yml@3c3600089c0ed4662058ac3660dde583a083db1a
    secrets: inherit
